name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "const config = { GITHUB_TOKEN: '${{ secrets.TOKEN }}', REPO_OWNER: 'tenstudiosbc', REPO_NAME: 'ssiavanguardchronicles' };" > config.js
          # Add your build steps here if needed

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
